from dataclasses import dataclass

@dataclass
class DesignElement:
    """Level Design Element that provides a string that can be loaded onto the list of bubbles.
    If treat_as_fill is True, make sure to provide an output that will run from the first bubble.
    If not, provide the output in a 2D list with a list per row. Remember to use leading zeroes in your designs when needed."""
    name: str
    cost: int
    chance_weight: int
    keywords: list
    output: list
    treat_as_fill: bool = False
    override: bool = True

@dataclass
class Fill:
    """Level Design Fill that can be used to fill in the spaces between design elements."""
    name: str
    cost: int
    chance_weight: int
    output: list
    keywords: list
    override: bool = False


DESIGNS = [ # These are based on default field width and height
    DesignElement(name = 'torii', cost = 6, chance_weight = 1, treat_as_fill = True,
                  keywords = ['fill', 'japan'],
                  output = [0, 0, 0, 0, 0, 0, 0, 0,
                             0, 0, 0, 0, 0, 0, 0,
                            2, 0, 0, 0, 0, 0, 0, 2, 
                             2, 2, 2, 2, 2, 2, 2, 
                            0, 0, 2, 0, 0, 2, 0, 0, 
                             0, 2, 2, 2, 2, 2, 0, 
                            0, 2, 0, 0, 0, 0 ,2, 0, 
                             2, 0, 0, 0, 0, 0, 2]),
    DesignElement(name = 'fireworks', cost = 3, chance_weight= 1,
                  keywords = ['locked'],
                  output = [[0, 24, 24],
                             [24, 97, 24],]),
    DesignElement(name = 'cloud', cost = 3, chance_weight= 1,
                  keywords = [],
                  output = [[0, 7, 7],
                             [7, 7, 7],]),
    DesignElement(name = 'cloudJP', cost = 3, chance_weight= 1,
                  keywords = ['japan'],
                  output = [[7, 7, 7, 7],
                             [0, 0, 7],
                            [0, 7, 7, 7, 7]]),
    DesignElement(name = 'cherrytree', cost = 3, chance_weight= 1,
                  keywords = ['japan'],
                  output = [[0, 5, 5, 0],
                             [5, 5, 5],
                            [5, 1, 1, 0],
                             [0, 1, 5],
                            [0, 1, 1, 0],
                             [0, 1, 0],
                            [0, 1, 1, 0]]),
    DesignElement(name = 'pinetree', cost = 3, chance_weight= 1,
                  keywords = [],
                  output = [[0, 0, 0, 0],
                             [0, 9, 0],
                            [0, 9, 9, 0],
                             [9, 9, 9],
                            [9, 9, 9, 9],
                             [0, 1, 0],
                            [0, 1, 1, 0]]),
    DesignElement(name = 'tree', cost = 3, chance_weight= 1,
                  keywords = [],
                  output = [[0, 9, 9, 0],
                             [9, 9, 9],
                            [9, 1, 9, 9],
                             [0, 1, 9],
                            [0, 1, 1, 0],
                             [0, 1, 0],
                            [0, 1, 1, 0]]),
    DesignElement(name = 'mountain', cost = 6, chance_weight = 1, treat_as_fill = True,
                  keywords = ['fill', 'japan'],
                  output = [0, 0, 0, 2, 2, 0, 0, 0,
                             0, 0, 2, 7, 2, 0, 0,
                            0, 0, 0, 7, 7, 0, 0, 0, 
                             0, 0, 8, 7, 8, 0, 0, 
                            0, 0, 8, 8, 8, 8, 0, 0, 
                             0, 8, 8, 8, 8, 8, 0, 
                            0, 8, 8, 8, 8, 8 ,8, 0, 
                             8, 8, 8, 8, 8, 8, 8]),
    DesignElement(name = 'bridge', cost = 6, chance_weight = 1, treat_as_fill = True,
                  keywords = ['fill'],
                  output = [0, 0, 0, 0, 0, 0, 0, 0,
                             0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 
                             0, 0, 0, 0, 0, 0, 0, 
                            0, 7, 0, 0, 0, 0, 7, 0, 
                             8, 8, 8, 8, 8, 8, 8, 
                            7, 7, 0, 0, 0, 0, 7, 7, 
                             7, 0, 0, 0, 0, 0, 7]),
    DesignElement(name = 'windmill', cost = 3, chance_weight= 1,
                  keywords = ['ned'],
                  output = [[7, 0, 0, 7],
                             [7, 1, 7],
                            [0, 7, 7],
                             [7, 1, 7],
                            [7, 1, 1, 7]]), 
]

FILLS = [   # These are based on default field width and height
    Fill(name = 'ireland', cost = 1, chance_weight = 4, 
         keywords = ['flag', 'ire'],
         output =[9, 9, 7, 7, 7, 7, 3, 3,
                   9, 9, 7, 7, 7, 3, 3,
                  9, 9, 7, 7, 7, 7, 3, 3,
                   9, 9, 7, 7, 7, 3, 3,
                  9, 9, 7, 7, 7, 7, 3, 3,
                   9, 9, 7, 7, 7, 3, 3,
                  9, 9, 7, 7, 7, 7, 3, 3]),
    Fill(name = 'netherlands', cost = 1, chance_weight = 4, 
         keywords = ['flag', 'ned'],
         output =[2, 2, 2, 2, 2, 2, 2, 2,
                   2, 2, 2, 2, 2, 2, 2,
                  7, 7, 7, 7, 7, 7, 7, 7,
                   7, 7, 7, 7, 7, 7, 7,
                  6, 6, 6, 6, 6, 6, 6, 6,
                   6, 6, 6, 6, 6, 6, 6,
                  0, 0, 0, 0, 0, 0, 0, 0]),
    Fill(name = 'japan', cost = 1, chance_weight = 4, 
         keywords = ['flag', 'japan'],
         output =[7, 7, 7, 7, 7, 7, 7, 7,
                   7, 7, 7, 7, 7, 7, 7,
                  7, 7, 7, 2, 2, 7, 7, 7,
                   7, 7, 2, 2, 2, 7, 7,
                  7, 7, 7, 2, 2, 7, 7, 7,
                   7, 7, 7, 7, 7, 7, 7,
                  7, 7, 7, 7, 7, 7, 7, 7]),
    Fill(name = 'ustates', cost = 1, chance_weight = 4, 
         keywords = ['flag', 'usa'],
         output =[7, 6, 6, 2, 2, 2, 2, 2,
                   6, 2, 6, 7, 7, 7, 7,
                  6, 6, 6, 2, 2, 2, 2, 2,
                   7, 7, 7, 7, 7, 7, 7,
                  2, 2, 2, 2, 2, 2, 2, 2,
                   0, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0]),
    Fill(name = 'australia', cost = 1, chance_weight = 4, 
         keywords = ['flag', 'aus'],
         output =[2, 6, 2, 6, 6, 6, 6, 6,
                   2, 2, 6, 6, 7, 6, 6,
                  2, 6, 2, 6, 6, 6, 7, 6,
                   6, 6, 6, 7, 6, 7, 6,
                  6, 7, 7, 6, 6, 6, 6, 6,
                   6, 7, 6, 6, 7, 6, 6,
                  6, 6, 6, 6, 6, 6, 6, 6]),
    Fill(name = 'skyground', cost = 1, chance_weight = 4, 
         keywords = ['day', 'night'],
         output =[6, 6, 6, 6, 6, 6, 6, 6,
                   6, 6, 6, 6, 6, 6, 6,
                  6, 6, 6, 6, 6, 6, 6, 6,
                   1, 1, 1, 1, 1, 1, 1,
                  8, 8, 8, 8, 8, 8, 8, 8,
                   0, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0]),
    Fill(name = 'skygroundDUSK', cost = 1, chance_weight = 4, 
         keywords = ['dusk'],
         output =[3, 3, 3, 3, 3, 3, 3, 3,
                   3, 3, 3, 3, 3, 3, 3,
                  3, 3, 3, 3, 3, 3, 3, 3,
                   1, 1, 1, 1, 1, 1, 1,
                  8, 8, 8, 8, 8, 8, 8, 8,
                   0, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0]),
    Fill(name = 'city', cost = 1, chance_weight = 4, 
         keywords = [],
         output =[6, 6, 6, 6, 6, 6, 6, 6,
                   6, 6, 6, 6, 6, 6, 6,
                  6, 8, 6, 6, 6, 6, 8, 8,
                   8, 8, 6, 8, 6, 8, 8,
                  8, 8, 0, 8, 0, 0, 8, 8,
                   8, 8, 0, 8, 0, 8, 8,
                  0, 0, 0, 0, 0, 0, 0, 0]),
    Fill(name = 'frame', cost = 1, chance_weight = 4, override = True, 
         keywords = ['museum'],
         output =[1, 1, 1, 8, 8, 1, 1, 1,
                   1, 0, 0, 0, 0, 0, 1,
                  1, 0, 0, 0, 0, 0, 0, 1,
                   8, 0, 0, 0, 0, 0, 8,
                  8, 0, 0, 0, 0, 0, 0, 8,
                   1, 0, 0, 0, 0, 0, 1,
                  1, 0, 0, 0, 0, 0, 0, 1,
                   1, 1, 8, 8, 8, 1, 1]),
    # Name goes 'diagonal[Direction (L/R)][number of colors]'
    Fill(name = 'diagonalR2', cost = 1, chance_weight = 4, override = True, 
         keywords = ['diagonal'],
         output =['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B',
                     'A', 'B', 'A', 'B', 'A', 'B', 'A',
                  'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A',
                     'B', 'A', 'B', 'A', 'B', 'A', 'B',
                  'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B',
                     'A', 'B', 'A', 'B', 'A', 'B', 'A',
                  'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A',
                     'B', 'A', 'B', 'A', 'B', 'A', 'B']),
    #Fill(name = 'diagonalR3', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['diagonal'],
    #     output =[A, B, C, A, B, C, A, B,
    #               A, B, C, A, B, C, A,
    #              C, A, B, C, A, B, C, A,
    #               C, A, B, C, A, B, C,
    #              B, C, A, B, C, A, B, C,
    #               B, C, A, B, C, A, B,
    #              A, B, C, A, B, C, A, B,
    #               A, B, C, A, B, C, A]),
    #Fill(name = 'diagonalR4', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['diagonal'],
    #     output =[A, B, C, D, A, B, C, D,
    #               A, B, C, D, A, B, C,
    #              D, A, B, C, D, A, B, C,
    #               D, A, B, C, D, A, B,
    #              C, D, A, B, C, D, A, B,
    #               C, D, A, B, C, D, A,
    #              B, C, D, A, B, C, D, A,
    #               B, C, D, A, B, C, D]),
    #Fill(name = 'diagonalL2', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['diagonal'],
    #     output =[B, A, B, A, B, A, B, A,
    #               A, B, A, B, A, B, A,
    #              A, B, A, B, A, B, A, B,
    #               B, A, B, A, B, A, B,
    #              B, A, B, A, B, A, B, A,
    #               A, B, A, B, A, B, A,
    #              A, B, A, B, A, B, A, B,
    #               B, A, B, A, B, A, B]),
    #Fill(name = 'diagonalL3', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['diagonal'],
    #     output =[B, A, C, B, A, C, B, A,
    #               A, C, B, A, C, B, A,
    #              A, C, B, A, C, B, A, C,
    #               C, B, A, C, B, A, C,
    #              C, B, A, C, B, A, C, B,
    #               B, A, C, B, A, C, B,
    #              B, A, C, B, A, C, B, A,
    #               A, C, B, A, C, B, A]),
    #Fill(name = 'diagonalL4', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['diagonal'],
    #     output =[D, C, B, A, D, C, B, A,
    #               C, B, A, D, C, B, A,
    #              C, B, A, D, C, B, A, D,
    #               B, A, D, C, B, A, D,
    #              B, A, D, C, B, A, D, C,
    #               A, D, C, B, A, D, C,
    #              A, D, C, B, A, D, C, B,
    #               D, C, B, A, D, C, B]),
    #Fill(name = 'columns2narrow', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['column'],
    #     output =[A, B, A, B, A, B, A, B,
    #               A, B, A, B, A, B, A,
    #              A, B, A, B, A, B, A, B,
    #               A, B, A, B, A, B, A,
    #              A, B, A, B, A, B, A, B,
    #               A, B, A, B, A, B, A,
    #              A, B, A, B, A, B, A, B,
    #               A, B, A, B, A, B, A]),
    #Fill(name = 'columns2broad', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['column'],
    #     output =[A, A, B, B, A, A, B, B,
    #               A, A, B, B, A, A, B,
    #              A, A, B, B, A, A, B, B,
    #               A, A, B, B, A, A, B,
    #              A, A, B, B, A, A, B, B,
    #               A, A, B, B, A, A, B,
    #              A, A, B, B, A, A, B, B,
    #               A, A, B, B, A, A, B]),
    #Fill(name = 'columns3', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['column'],
    #     output =[A, B, C, A, B, C, A, B,
    #               A, B, C, A, B, C, A,
    #              A, B, C, A, B, C, A, B,
    #               A, B, C, A, B, C, A,
    #              A, B, C, A, B, C, A, B,
    #               A, B, C, A, B, C, A,
    #              A, B, C, A, B, C, A, B,
    #               A, B, C, A, B, C, A]),
    #Fill(name = 'columns4', cost = 1, chance_weight = 4, override = True, 
    #     keywords = ['column'],
    #     output =[A, B, C, D, A, B, C, D,
    #               A, B, C, D, A, B, C,
    #              A, B, C, D, A, B, C, D,
    #               A, B, C, D, A, B, C,
    #              A, B, C, D, A, B, C, D,
    #               A, B, C, D, A, B, C,
    #              A, B, C, D, A, B, C, D,
    #               A, B, C, D, A, B, C]),
]